language: node_js
node_js:
  - "10"

services:
  - docker

cache:
  directories:
    - node_modules

matrix:
  fast_finish: true

before_install:
  - npm install -g npm
  - npm install -g codacy-coverage release-it greenkeeper-lockfile ganache-cli@~6.1.8

before_script:
  - greenkeeper-lockfile-update
  - ganache-cli --port 18545 > ganache-cli.log &
  - git clone https://github.com/oceanprotocol/barge
  - cd barge
  - export KEEPER_VERSION=v0.9.0
  - export KEEPER_OWNER_ROLE_ADDRESS="0xe2DD09d719Da89e5a3D0F2549c7E24566e947260"
  - bash -x start_ocean.sh --latest --no-pleuston --local-spree-node 2>&1 > start_ocean.log &
  - cd ..
  - ./scripts/unlock-spree-accounts.sh  2>&1 > /dev/null &

script:
  - export ETH_PORT=18545; npm run test:cover
  - npm run build
  - npm run doc
  - ./scripts/wait_for_migration_and_extract_keeper_artifacts.sh
  - npm run integration:cover
  - npm run merge-coverages
  - npm run report-coverage

after_script:
  - greenkeeper-lockfile-upload

notifications:
  email: false

deploy:
  - provider: npm
    email: "devops@oceanprotocol.com"
    api_key: ${NPM_TOKEN}
    skip_cleanup: true
    on:
      tags: true

